import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  await prisma.districtMetric.deleteMany();
  await prisma.recommendation.deleteMany();
  await prisma.residueListing.deleteMany();
  await prisma.biomassBuyer.deleteMany();
  await prisma.machineryBooking.deleteMany();
  await prisma.machinery.deleteMany();
  await prisma.harvestRecord.deleteMany();
  await prisma.farm.deleteMany();
  await prisma.user.deleteMany();

  const users = await Promise.all([
    prisma.user.create({
      data: {
        name: 'Amarjeet Kaur',
        phone: '+91 98123 45678',
        role: 'FARMER',
        preferredLanguage: 'en',
        village: 'Badi Khera',
        district: 'Patiala',
        state: 'Punjab',
      },
    }),
    prisma.user.create({
      data: {
        name: 'Vijay Singh',
        phone: '+91 98120 65432',
        role: 'FARMER',
        preferredLanguage: 'en',
        village: 'Kotla Sultan Singh',
        district: 'Ludhiana',
        state: 'Punjab',
      },
    }),
    prisma.user.create({
      data: {
        name: 'Harpreet Kaur',
        phone: '+91 98111 11223',
        role: 'FARMER',
        preferredLanguage: 'hi',
        village: 'Mullanpur Dakha',
        district: 'Ludhiana',
        state: 'Punjab',
      },
    }),
    prisma.user.create({
      data: {
        name: 'Sukhwinder Singh',
        phone: '+91 98122 33445',
        role: 'FARMER',
        preferredLanguage: 'pa',
        village: 'Bhikhiwind',
        district: 'Amritsar',
        state: 'Punjab',
      },
    }),
    prisma.user.create({
      data: {
        name: 'Gurdeep Kaur',
        phone: '+91 98133 55667',
        role: 'FARMER',
        preferredLanguage: 'en',
        village: 'Sangrur',
        district: 'Sangrur',
        state: 'Punjab',
      },
    }),
    prisma.user.create({
      data: {
        name: 'Rajinder Singh',
        phone: '+91 98144 77889',
        role: 'FARMER',
        preferredLanguage: 'hi',
        village: 'Moga',
        district: 'Moga',
        state: 'Punjab',
      },
    }),
    prisma.user.create({
      data: {
        name: 'Kiran Devi',
        phone: '+91 98155 12345',
        role: 'FARMER',
        preferredLanguage: 'pa',
        village: 'Nawanshahr',
        district: 'Sangrur',
        state: 'Punjab',
      },
    }),
    prisma.user.create({
      data: {
        name: 'Balbir Singh',
        phone: '+91 98166 23456',
        role: 'FARMER',
        preferredLanguage: 'en',
        village: 'Rampura Phul',
        district: 'Bathinda',
        state: 'Punjab',
      },
    }),
    prisma.user.create({
      data: {
        name: 'Harminder Sharma',
        phone: '+91 98155 99001',
        role: 'PROVIDER',
        preferredLanguage: 'en',
        village: 'Patiala',
        district: 'Patiala',
        state: 'Punjab',
      },
    }),
    prisma.user.create({
      data: {
        name: 'Amandeep Kaur',
        phone: '+91 98166 22334',
        role: 'PROVIDER',
        preferredLanguage: 'pa',
        village: 'Bathinda',
        district: 'Bathinda',
        state: 'Punjab',
      },
    }),
    prisma.user.create({
      data: {
        name: 'Jaspreet Singh',
        phone: '+91 98177 44556',
        role: 'COORDINATOR',
        preferredLanguage: 'en',
        village: 'Patiala',
        district: 'Patiala',
        state: 'Punjab',
      },
    }),
  ]);

  const farmers = users.filter((user) => user.role === 'FARMER');
  const providers = users.filter((user) => user.role === 'PROVIDER');

  const farms = await Promise.all([
    prisma.farm.create({
      data: {
        farmerId: farmers[0].id,
        farmName: 'Amarjeet Farm',
        areaInAcres: 5,
        latitude: 30.3322,
        longitude: 76.3821,
        soilType: 'Loamy',
        irrigationType: 'Canal',
        currentCrop: 'Paddy',
        cropStage: 'Harvested',
      },
    }),
    prisma.farm.create({
      data: {
        farmerId: farmers[1].id,
        farmName: 'Vijay Farm',
        areaInAcres: 8,
        latitude: 30.9000,
        longitude: 75.8573,
        soilType: 'Sandy loam',
        irrigationType: 'Tube well',
        currentCrop: 'Paddy',
        cropStage: 'Harvesting',
      },
    }),
    prisma.farm.create({
      data: {
        farmerId: farmers[2].id,
        farmName: 'Harpreet Fields',
        areaInAcres: 6,
        latitude: 30.8134,
        longitude: 75.6048,
        soilType: 'Clay loam',
        irrigationType: 'Canal',
        currentCrop: 'Paddy',
        cropStage: 'Harvested',
      },
    }),
    prisma.farm.create({
      data: {
        farmerId: farmers[3].id,
        farmName: 'Sukhwinder Farm',
        areaInAcres: 4,
        latitude: 31.6360,
        longitude: 74.8723,
        soilType: 'Silty loam',
        irrigationType: 'Rainfed',
        currentCrop: 'Paddy',
        cropStage: 'Harvesting',
      },
    }),
    prisma.farm.create({
      data: {
        farmerId: farmers[4].id,
        farmName: 'Gurdeep Fields',
        areaInAcres: 10,
        latitude: 30.2450,
        longitude: 75.8414,
        soilType: 'Loam',
        irrigationType: 'Canal',
        currentCrop: 'Maize',
        cropStage: 'Growing',
      },
    }),
    prisma.farm.create({
      data: {
        farmerId: farmers[5].id,
        farmName: 'Rajinder Farm',
        areaInAcres: 7,
        latitude: 30.8160,
        longitude: 75.1751,
        soilType: 'Sandy loam',
        irrigationType: 'Tube well',
        currentCrop: 'Paddy',
        cropStage: 'Harvested',
      },
    }),
    prisma.farm.create({
      data: {
        farmerId: farmers[6].id,
        farmName: 'Kiran’s Plot',
        areaInAcres: 3.5,
        latitude: 30.1000,
        longitude: 76.0000,
        soilType: 'Loam',
        irrigationType: 'Tube well',
        currentCrop: 'Mustard',
        cropStage: 'Maturing',
      },
    }),
    prisma.farm.create({
      data: {
        farmerId: farmers[7].id,
        farmName: 'Balbir Orchard',
        areaInAcres: 4.5,
        latitude: 30.2100,
        longitude: 74.9800,
        soilType: 'Clay loam',
        irrigationType: 'Canal',
        currentCrop: 'Pulses',
        cropStage: 'Sowing',
      },
    }),
    prisma.farm.create({
      data: {
        farmerId: farmers[0].id,
        farmName: 'Amarjeet East Field',
        areaInAcres: 2.5,
        latitude: 30.3340,
        longitude: 76.3850,
        soilType: 'Loamy',
        irrigationType: 'Canal',
        currentCrop: 'Vegetables',
        cropStage: 'Growing',
      },
    }),
    prisma.farm.create({
      data: {
        farmerId: farmers[1].id,
        farmName: 'Vijay South Plot',
        areaInAcres: 5,
        latitude: 30.9020,
        longitude: 75.8600,
        soilType: 'Sandy loam',
        irrigationType: 'Tube well',
        currentCrop: 'Cotton',
        cropStage: 'Flowering',
      },
    }),
    prisma.farm.create({
      data: {
        farmerId: farmers[2].id,
        farmName: 'Harpreet North Farm',
        areaInAcres: 4,
        latitude: 30.8150,
        longitude: 75.6070,
        soilType: 'Clay loam',
        irrigationType: 'Canal',
        currentCrop: 'Paddy',
        cropStage: 'Harvested',
      },
    }),
    prisma.farm.create({
      data: {
        farmerId: farmers[3].id,
        farmName: 'Sukhwinder Garden',
        areaInAcres: 3,
        latitude: 31.6380,
        longitude: 74.8700,
        soilType: 'Silty loam',
        irrigationType: 'Rainfed',
        currentCrop: 'Pulses',
        cropStage: 'Maturing',
      },
    }),
  ]);

  await Promise.all([
    prisma.harvestRecord.create({
      data: {
        farmId: farms[0].id,
        crop: 'Paddy',
        harvestDate: new Date('2026-10-01'),
        estimatedYieldTonnes: 6.2,
        estimatedResidueTonnes: 18.6,
        residueStatus: 'Fresh stubble',
      },
    }),
    prisma.harvestRecord.create({
      data: {
        farmId: farms[1].id,
        crop: 'Paddy',
        harvestDate: new Date('2026-10-04'),
        estimatedYieldTonnes: 9.8,
        estimatedResidueTonnes: 29.4,
        residueStatus: 'Drying',
      },
    }),
    prisma.harvestRecord.create({
      data: {
        farmId: farms[2].id,
        crop: 'Paddy',
        harvestDate: new Date('2026-09-28'),
        estimatedYieldTonnes: 7.4,
        estimatedResidueTonnes: 22.2,
        residueStatus: 'Harvested',
      },
    }),
    prisma.harvestRecord.create({
      data: {
        farmId: farms[3].id,
        crop: 'Paddy',
        harvestDate: new Date('2026-10-02'),
        estimatedYieldTonnes: 4.8,
        estimatedResidueTonnes: 14.4,
        residueStatus: 'Fresh stubble',
      },
    }),
  ]);

  await prisma.machinery.createMany({
    data: [
      {
        providerId: providers[0].id,
        name: 'Happy Seeder A1',
        type: 'Seeder',
        pricePerAcre: 2200,
        latitude: 30.3380,
        longitude: 76.3860,
        village: 'Badi Khera',
        district: 'Patiala',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-01').toISOString(),
        availableUntil: new Date('2026-12-31').toISOString(),
      },
      {
        providerId: providers[0].id,
        name: 'Rotavator B2',
        type: 'Tillage',
        pricePerAcre: 1200,
        latitude: 30.3400,
        longitude: 76.3900,
        village: 'Badi Khera',
        district: 'Patiala',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-01').toISOString(),
        availableUntil: new Date('2026-12-31').toISOString(),
      },
      {
        providerId: providers[0].id,
        name: 'Super Seeder A2',
        type: 'Seeder',
        pricePerAcre: 2600,
        latitude: 30.3440,
        longitude: 76.4120,
        village: 'Kotla Sultan Singh',
        district: 'Ludhiana',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-01').toISOString(),
        availableUntil: new Date('2026-12-31').toISOString(),
      },
      {
        providerId: providers[0].id,
        name: 'Happy Seeder A3',
        type: 'Seeder',
        pricePerAcre: 2400,
        latitude: 30.3350,
        longitude: 76.3810,
        village: 'Badi Khera',
        district: 'Patiala',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-03').toISOString(),
        availableUntil: new Date('2026-12-31').toISOString(),
      },
      {
        providerId: providers[0].id,
        name: 'Straw Baler A4',
        type: 'Baler',
        pricePerAcre: 2800,
        latitude: 30.3325,
        longitude: 76.3880,
        village: 'Badi Khera',
        district: 'Patiala',
        availabilityStatus: 'BOOKED',
        availableFrom: new Date('2026-10-05').toISOString(),
        availableUntil: new Date('2026-12-20').toISOString(),
      },
      {
        providerId: providers[1].id,
        name: 'Paddy Straw Baler',
        type: 'Baler',
        pricePerAcre: 2800,
        latitude: 30.2165,
        longitude: 74.9455,
        village: 'Bathinda',
        district: 'Bathinda',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-01').toISOString(),
        availableUntil: new Date('2026-12-31').toISOString(),
      },
      {
        providerId: providers[1].id,
        name: 'Balers',
        type: 'Baler',
        pricePerAcre: 2500,
        latitude: 30.2217,
        longitude: 74.9455,
        village: 'Bathinda',
        district: 'Bathinda',
        availabilityStatus: 'BOOKED',
        availableFrom: new Date('2026-10-05').toISOString(),
        availableUntil: new Date('2026-12-15').toISOString(),
      },
      {
        providerId: providers[1].id,
        name: 'Tractor Mounted Seeder',
        type: 'Seeder',
        pricePerAcre: 2000,
        latitude: 30.2180,
        longitude: 74.9460,
        village: 'Bathinda',
        district: 'Bathinda',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-02').toISOString(),
        availableUntil: new Date('2026-12-30').toISOString(),
      },
      {
        providerId: providers[1].id,
        name: 'Chopper B6',
        type: 'Chopper',
        pricePerAcre: 1500,
        latitude: 30.2250,
        longitude: 74.9400,
        village: 'Bathinda',
        district: 'Bathinda',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-01').toISOString(),
        availableUntil: new Date('2026-12-31').toISOString(),
      },
      {
        providerId: providers[0].id,
        name: 'Power Harrow',
        type: 'Tillage',
        pricePerAcre: 1300,
        latitude: 30.3390,
        longitude: 76.3870,
        village: 'Kotla Sultan Singh',
        district: 'Ludhiana',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-05').toISOString(),
        availableUntil: new Date('2026-12-30').toISOString(),
      },
      {
        providerId: providers[0].id,
        name: 'Sprayer',
        type: 'Sprayer',
        pricePerAcre: 900,
        latitude: 30.3420,
        longitude: 76.3920,
        village: 'Kotla Sultan Singh',
        district: 'Ludhiana',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-01').toISOString(),
        availableUntil: new Date('2026-12-31').toISOString(),
      },
      {
        providerId: providers[1].id,
        name: 'Seed Drill',
        type: 'Seeder',
        pricePerAcre: 2100,
        latitude: 30.2190,
        longitude: 74.9490,
        village: 'Bathinda',
        district: 'Bathinda',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-01').toISOString(),
        availableUntil: new Date('2026-12-31').toISOString(),
      },
      {
        providerId: providers[0].id,
        name: 'Mulcher',
        type: 'Mulcher',
        pricePerAcre: 1800,
        latitude: 30.3360,
        longitude: 76.3885,
        village: 'Badi Khera',
        district: 'Patiala',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-01').toISOString(),
        availableUntil: new Date('2026-12-31').toISOString(),
      },
      {
        providerId: providers[0].id,
        name: 'Field Roller',
        type: 'Roller',
        pricePerAcre: 1000,
        latitude: 30.3370,
        longitude: 76.3890,
        village: 'Patiala',
        district: 'Patiala',
        availabilityStatus: 'AVAILABLE',
        availableFrom: new Date('2026-10-10').toISOString(),
        availableUntil: new Date('2026-12-15').toISOString(),
      },
    ],
  });

  await prisma.biomassBuyer.createMany({
    data: [
      {
        name: 'Green Energy Hub',
        buyerType: 'Power Plant',
        acceptedResidueTypes: 'Paddy straw',
        pricePerTonne: 2800,
        capacityTonnes: 150,
        latitude: 30.3461,
        longitude: 76.3916,
        village: 'Patiala',
        district: 'Patiala',
        contactPhone: '+91 98100 11223',
        status: 'OPEN',
      },
      {
        name: 'Biochar Co-op',
        buyerType: 'Compost',
        acceptedResidueTypes: 'Paddy straw, Maize stalk',
        pricePerTonne: 2400,
        capacityTonnes: 90,
        latitude: 30.2200,
        longitude: 74.9400,
        village: 'Bathinda',
        district: 'Bathinda',
        contactPhone: '+91 98111 33445',
        status: 'OPEN',
      },
      {
        name: 'Local Biomass Depot',
        buyerType: 'Feed mill',
        acceptedResidueTypes: 'Paddy straw',
        pricePerTonne: 2600,
        capacityTonnes: 120,
        latitude: 30.8950,
        longitude: 75.8610,
        village: 'Ludhiana',
        district: 'Ludhiana',
        contactPhone: '+91 98122 55667',
        status: 'OPEN',
      },
      {
        name: 'Soil Health Buyer',
        buyerType: 'Compost',
        acceptedResidueTypes: 'Paddy straw, Cotton stalk',
        pricePerTonne: 2300,
        capacityTonnes: 80,
        latitude: 30.1500,
        longitude: 75.8000,
        village: 'Patiala',
        district: 'Patiala',
        contactPhone: '+91 98133 77889',
        status: 'OPEN',
      },
      {
        name: 'Green Pellet Works',
        buyerType: 'Pellet plant',
        acceptedResidueTypes: 'Paddy straw',
        pricePerTonne: 2700,
        capacityTonnes: 100,
        latitude: 30.9000,
        longitude: 75.8600,
        village: 'Ludhiana',
        district: 'Ludhiana',
        contactPhone: '+91 98144 88990',
        status: 'OPEN',
      },
      {
        name: 'Sangrur Biomass Yard',
        buyerType: 'Feed mill',
        acceptedResidueTypes: 'Paddy straw, Maize stalk',
        pricePerTonne: 2500,
        capacityTonnes: 110,
        latitude: 30.2450,
        longitude: 75.8414,
        village: 'Sangrur',
        district: 'Sangrur',
        contactPhone: '+91 98155 99002',
        status: 'OPEN',
      },
      {
        name: 'Moga Straw Hub',
        buyerType: 'Bioenergy',
        acceptedResidueTypes: 'Paddy straw',
        pricePerTonne: 2550,
        capacityTonnes: 95,
        latitude: 30.8160,
        longitude: 75.1751,
        village: 'Moga',
        district: 'Moga',
        contactPhone: '+91 98166 11122',
        status: 'OPEN',
      },
      {
        name: 'Amritsar Agri Buyer',
        buyerType: 'Compost',
        acceptedResidueTypes: 'Paddy straw',
        pricePerTonne: 2350,
        capacityTonnes: 105,
        latitude: 31.6360,
        longitude: 74.8723,
        village: 'Amritsar',
        district: 'Amritsar',
        contactPhone: '+91 98177 22233',
        status: 'OPEN',
      },
      {
        name: 'Patiala Pellet Plant',
        buyerType: 'Pellet plant',
        acceptedResidueTypes: 'Paddy straw',
        pricePerTonne: 2850,
        capacityTonnes: 130,
        latitude: 30.3322,
        longitude: 76.3821,
        village: 'Patiala',
        district: 'Patiala',
        contactPhone: '+91 98188 33344',
        status: 'OPEN',
      },
      {
        name: 'Punjab Feed Supply',
        buyerType: 'Feed mill',
        acceptedResidueTypes: 'Paddy straw, Maize stalk',
        pricePerTonne: 2450,
        capacityTonnes: 95,
        latitude: 30.8134,
        longitude: 75.6048,
        village: 'Ludhiana',
        district: 'Ludhiana',
        contactPhone: '+91 98199 44455',
        status: 'OPEN',
      },
    ],
  });

  await prisma.recommendation.createMany({
    data: farms.map((farm, index) => ({
      farmId: farm.id,
      recommendationType: 'MACHINERY_BOOKING',
      title: `Use machinery for ${farm.currentCrop}`,
      explanation: `Nearby machines, weather, and residue status suggest a low-risk residue plan for ${farm.currentCrop}.`,      
      priority: 2,
      confidence: 0.78,
      estimatedWaterSaving: farm.currentCrop === 'Paddy' ? 90 : 40,
      estimatedIncomeChange: farm.currentCrop === 'Paddy' ? 1250 : 700,
      actionLabel: 'View nearby machinery',
      status: 'ACTIVE',
    })),
  });

  await prisma.districtMetric.createMany({
    data: [
      {
        district: 'Patiala',
        state: 'Punjab',
        residueTonnes: 1800,
        estimatedBurningRisk: 72,
        machineryAvailable: 14,
        machineryRequired: 22,
        biomassDemandTonnes: 1200,
        estimatedAvoidedBurning: 650,
      },
      {
        district: 'Ludhiana',
        state: 'Punjab',
        residueTonnes: 2400,
        estimatedBurningRisk: 80,
        machineryAvailable: 10,
        machineryRequired: 30,
        biomassDemandTonnes: 1500,
        estimatedAvoidedBurning: 820,
      },
      {
        district: 'Bathinda',
        state: 'Punjab',
        residueTonnes: 1300,
        estimatedBurningRisk: 68,
        machineryAvailable: 8,
        machineryRequired: 18,
        biomassDemandTonnes: 900,
        estimatedAvoidedBurning: 430,
      },
      {
        district: 'Amritsar',
        state: 'Punjab',
        residueTonnes: 1500,
        estimatedBurningRisk: 65,
        machineryAvailable: 11,
        machineryRequired: 20,
        biomassDemandTonnes: 1000,
        estimatedAvoidedBurning: 520,
      },
      {
        district: 'Sangrur',
        state: 'Punjab',
        residueTonnes: 1700,
        estimatedBurningRisk: 70,
        machineryAvailable: 12,
        machineryRequired: 24,
        biomassDemandTonnes: 1100,
        estimatedAvoidedBurning: 600,
      },
      {
        district: 'Moga',
        state: 'Punjab',
        residueTonnes: 1200,
        estimatedBurningRisk: 62,
        machineryAvailable: 9,
        machineryRequired: 17,
        biomassDemandTonnes: 800,
        estimatedAvoidedBurning: 390,
      },
    ],
  });

  console.log('Seed completed');
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
